apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.env.DEBUG | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | quote }}
  ALLOWED_HOSTS: {{ .Values.env.ALLOWED_HOSTS | quote }}
  STATIC_URL: {{ .Values.env.STATIC_URL | quote }}
  STATIC_ROOT: {{ .Values.env.STATIC_ROOT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }} 