apiVersion: v2
name: django-app
description: A Helm chart for Django application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - django
  - python
  - web
home: https://github.com/icxodnik/DevOps_practice
sources:
  - https://github.com/icxodnik/DevOps_practice
maintainers:
  - name: Nataliia Khodorova
    email: icxodnik@gmail.com
