apiVersion: v2
name: django-app
description: Django застосунок для розгортання на Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - django
  - python
  - web
  - kubernetes
  - aws
